worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 768;
}

http {
    sendfile on;
    server_tokens off;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 127.0.0.1:80;
        server_name _;

        root /var/www/html;
        index index.php index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        }

        # Block hidden files
        location ~ /\. {
            deny all;
        }
    }
}
